version: '3'

services:
  server:
    build: ./server
    restart: always
    ports:
      - 5000:80

  client:
    build: ./client
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 3000:80
    depends_on:
      - server
